common:
  PORT: 10086
  PRJ_NAME: "${PRJNAME}"
  BASE_DOMAIN: "${PRJNAME}.pgc.huya.com"
  DOMAIN_PREFIX: ""
  PM2_LOG_DIR: "/data/logs/pm2"
  PASS_ONLINE: ""
  PASS_DEV: "#"

dev:
  PORT: 3000
  NODE_ENV: "dev"
  PM2_MODE: "fork"
  PASS_ONLINE: "#"
  PASS_DEV: ""
beta:
  NODE_ENV: "beta"
  DOMAIN_PREFIX: "beta."
  PM2_MODE: "cluster"
online:
  NODE_ENV: "online"
  PORT: 3000
  PM2_MODE: "cluster"
